# This workflow automatically creates a GitHub and PyPI release for the project on successful version update

name: Release Python project

on:
  push:
    tags:
      - 'v*'

jobs:
  lint:
    uses: diapolo10/.github/.github/workflows/publish-python.yml@c8ea0e99f7a5a688ae8f39d4f2163387f231ef1c
    with:
      python-versions: '["3.11", "3.12", "3.13", "3.14"]'
